# Generated by Django 4.2.7 on 2023-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
